export const STARTER_WORDS = [
  { id: "a2-001", term: "se présenter", translation: "خود را معرفی کردن", theme: "Identité et relations", example: "Je me présente : je m'appelle Masiha." },
  { id: "a2-002", term: "un voisin", translation: "همسایه", theme: "Identité et relations", example: "Mon voisin habite au troisième étage." },
  { id: "a2-003", term: "un collègue", translation: "همکار", theme: "Identité et relations", example: "Elle déjeune avec ses collègues." },
  { id: "a2-004", term: "s'entendre avec", translation: "با کسی تفاهم داشتن", theme: "Identité et relations", example: "Je m'entends bien avec ma famille." },
  { id: "a2-005", term: "rendre visite", translation: "به دیدن کسی رفتن", theme: "Identité et relations", example: "Nous rendons visite à nos amis." },
  { id: "a2-006", term: "célibataire", translation: "مجرد", theme: "Identité et relations", example: "Il est célibataire et vit seul." },
  { id: "a2-007", term: "généreux", translation: "سخاوتمند", theme: "Identité et relations", example: "C'est une personne très généreuse." },
  { id: "a2-008", term: "timide", translation: "خجالتی", theme: "Identité et relations", example: "Au début, elle paraît un peu timide." },
  { id: "a2-009", term: "faire connaissance", translation: "آشنا شدن", theme: "Identité et relations", example: "Nous avons fait connaissance au club." },
  { id: "a2-010", term: "avoir confiance", translation: "اعتماد داشتن", theme: "Identité et relations", example: "J'ai confiance en mon entraîneur." },

  { id: "a2-011", term: "se réveiller", translation: "بیدار شدن", theme: "Vie quotidienne", example: "Je me réveille à six heures." },
  { id: "a2-012", term: "se dépêcher", translation: "عجله کردن", theme: "Vie quotidienne", example: "Dépêche-toi, le bus arrive !" },
  { id: "a2-013", term: "d'habitude", translation: "معمولاً", theme: "Vie quotidienne", example: "D'habitude, je prépare mon petit-déjeuner." },
  { id: "a2-014", term: "de temps en temps", translation: "گاهی اوقات", theme: "Vie quotidienne", example: "Je cours de temps en temps." },
  { id: "a2-015", term: "être en retard", translation: "دیر رسیدن", theme: "Vie quotidienne", example: "Le train est encore en retard." },
  { id: "a2-016", term: "un rendez-vous", translation: "قرار ملاقات", theme: "Vie quotidienne", example: "J'ai un rendez-vous à quinze heures." },
  { id: "a2-017", term: "faire le ménage", translation: "خانه را تمیز کردن", theme: "Vie quotidienne", example: "Nous faisons le ménage le samedi." },
  { id: "a2-018", term: "se reposer", translation: "استراحت کردن", theme: "Vie quotidienne", example: "Après l'entraînement, je me repose." },
  { id: "a2-019", term: "prévoir", translation: "برنامه‌ریزی کردن", theme: "Vie quotidienne", example: "Que prévois-tu pour demain ?" },
  { id: "a2-020", term: "à l'heure", translation: "سر وقت", theme: "Vie quotidienne", example: "Elle arrive toujours à l'heure." },

  { id: "a2-021", term: "un immeuble", translation: "ساختمان چندطبقه", theme: "Logement et ville", example: "Cet immeuble est près du parc." },
  { id: "a2-022", term: "un quartier", translation: "محله", theme: "Logement et ville", example: "C'est un quartier calme et agréable." },
  { id: "a2-023", term: "un loyer", translation: "اجاره‌بها", theme: "Logement et ville", example: "Le loyer est assez cher ici." },
  { id: "a2-024", term: "déménager", translation: "اسباب‌کشی کردن", theme: "Logement et ville", example: "Nous allons déménager en septembre." },
  { id: "a2-025", term: "meublé", translation: "مبله", theme: "Logement et ville", example: "Je cherche un studio meublé." },
  { id: "a2-026", term: "une banlieue", translation: "حومهٔ شهر", theme: "Logement et ville", example: "Ils habitent en banlieue." },
  { id: "a2-027", term: "traverser", translation: "عبور کردن", theme: "Logement et ville", example: "Traversez la rue au feu vert." },
  { id: "a2-028", term: "tourner", translation: "پیچیدن", theme: "Logement et ville", example: "Tournez à gauche après la pharmacie." },
  { id: "a2-029", term: "tout droit", translation: "مستقیم", theme: "Logement et ville", example: "Continuez tout droit pendant cent mètres." },
  { id: "a2-030", term: "un trottoir", translation: "پیاده‌رو", theme: "Logement et ville", example: "Les piétons marchent sur le trottoir." },

  { id: "a2-031", term: "un trajet", translation: "مسیر رفت‌وآمد", theme: "Voyages et transports", example: "Le trajet dure environ deux heures." },
  { id: "a2-032", term: "un aller-retour", translation: "رفت‌وبرگشت", theme: "Voyages et transports", example: "Je voudrais un aller-retour pour Lyon." },
  { id: "a2-033", term: "un quai", translation: "سکوی قطار", theme: "Voyages et transports", example: "Le train part du quai numéro quatre." },
  { id: "a2-034", term: "rater", translation: "از دست دادن", theme: "Voyages et transports", example: "J'ai raté mon bus ce matin." },
  { id: "a2-035", term: "réserver", translation: "رزرو کردن", theme: "Voyages et transports", example: "Nous avons réservé une chambre." },
  { id: "a2-036", term: "un hébergement", translation: "محل اقامت", theme: "Voyages et transports", example: "Cet hébergement est proche de la mer." },
  { id: "a2-037", term: "des bagages", translation: "بار و چمدان", theme: "Voyages et transports", example: "Où puis-je laisser mes bagages ?" },
  { id: "a2-038", term: "à l'étranger", translation: "در خارج از کشور", theme: "Voyages et transports", example: "Elle veut étudier à l'étranger." },
  { id: "a2-039", term: "un séjour", translation: "اقامت یا سفر", theme: "Voyages et transports", example: "Notre séjour a duré une semaine." },
  { id: "a2-040", term: "atterrir", translation: "فرود آمدن", theme: "Voyages et transports", example: "L'avion va atterrir dans dix minutes." },

  { id: "a2-041", term: "faire les courses", translation: "خرید روزانه کردن", theme: "Alimentation et achats", example: "Je fais les courses au marché." },
  { id: "a2-042", term: "un rayon", translation: "بخش فروشگاه", theme: "Alimentation et achats", example: "Le lait est dans le rayon frais." },
  { id: "a2-043", term: "une réduction", translation: "تخفیف", theme: "Alimentation et achats", example: "Il y a une réduction de vingt pour cent." },
  { id: "a2-044", term: "un reçu", translation: "رسید خرید", theme: "Alimentation et achats", example: "Gardez votre reçu, s'il vous plaît." },
  { id: "a2-045", term: "rembourser", translation: "بازپرداخت کردن", theme: "Alimentation et achats", example: "Le magasin peut vous rembourser." },
  { id: "a2-046", term: "épicé", translation: "تند و پرادویه", theme: "Alimentation et achats", example: "Ce plat est trop épicé pour moi." },
  { id: "a2-047", term: "une entrée", translation: "پیش‌غذا", theme: "Alimentation et achats", example: "Comme entrée, je prends une salade." },
  { id: "a2-048", term: "commander", translation: "سفارش دادن", theme: "Alimentation et achats", example: "Nous sommes prêts à commander." },
  { id: "a2-049", term: "avoir faim", translation: "گرسنه بودن", theme: "Alimentation et achats", example: "Après le sport, j'ai très faim." },
  { id: "a2-050", term: "une recette", translation: "دستور غذا", theme: "Alimentation et achats", example: "Cette recette est facile à préparer." },

  { id: "a2-051", term: "être en forme", translation: "سرحال بودن", theme: "Santé et bien-être", example: "Je dors bien pour être en forme." },
  { id: "a2-052", term: "avoir mal à", translation: "درد داشتن", theme: "Santé et bien-être", example: "J'ai mal à la gorge depuis hier." },
  { id: "a2-053", term: "un médicament", translation: "دارو", theme: "Santé et bien-être", example: "Prenez ce médicament après le repas." },
  { id: "a2-054", term: "une ordonnance", translation: "نسخهٔ پزشک", theme: "Santé et bien-être", example: "Le médecin m'a donné une ordonnance." },
  { id: "a2-055", term: "tousser", translation: "سرفه کردن", theme: "Santé et bien-être", example: "Il tousse beaucoup cette nuit." },
  { id: "a2-056", term: "guérir", translation: "بهبود یافتن", theme: "Santé et bien-être", example: "Cette blessure va bientôt guérir." },
  { id: "a2-057", term: "se détendre", translation: "آرام شدن", theme: "Santé et bien-être", example: "La musique m'aide à me détendre." },
  { id: "a2-058", term: "un conseil", translation: "توصیه", theme: "Santé et bien-être", example: "Pouvez-vous me donner un conseil ?" },
  { id: "a2-059", term: "éviter", translation: "اجتناب کردن", theme: "Santé et bien-être", example: "Il faut éviter de se coucher tard." },
  { id: "a2-060", term: "respirer", translation: "نفس کشیدن", theme: "Santé et bien-être", example: "Respire lentement avant de commencer." },

  { id: "a2-061", term: "un emploi", translation: "شغل", theme: "Travail et études", example: "Elle cherche un emploi à temps partiel." },
  { id: "a2-062", term: "un entretien", translation: "مصاحبه", theme: "Travail et études", example: "J'ai un entretien lundi matin." },
  { id: "a2-063", term: "un salaire", translation: "حقوق", theme: "Travail et études", example: "Le salaire dépend de l'expérience." },
  { id: "a2-064", term: "une compétence", translation: "مهارت", theme: "Travail et études", example: "La communication est une compétence utile." },
  { id: "a2-065", term: "postuler", translation: "درخواست شغلی دادن", theme: "Travail et études", example: "Il va postuler pour ce poste." },
  { id: "a2-066", term: "réussir", translation: "موفق شدن", theme: "Travail et études", example: "Elle travaille beaucoup pour réussir." },
  { id: "a2-067", term: "échouer", translation: "شکست خوردن", theme: "Travail et études", example: "On peut apprendre même quand on échoue." },
  { id: "a2-068", term: "un diplôme", translation: "مدرک تحصیلی", theme: "Travail et études", example: "Il prépare un diplôme de français." },
  { id: "a2-069", term: "prendre des notes", translation: "یادداشت برداشتن", theme: "Travail et études", example: "Je prends des notes pendant le cours." },
  { id: "a2-070", term: "un devoir", translation: "تکلیف", theme: "Travail et études", example: "J'ai terminé mon devoir de français." },

  { id: "a2-071", term: "une exposition", translation: "نمایشگاه", theme: "Culture et loisirs", example: "Cette exposition ouvre demain." },
  { id: "a2-072", term: "un spectacle", translation: "نمایش", theme: "Culture et loisirs", example: "Nous avons vu un beau spectacle." },
  { id: "a2-073", term: "un abonnement", translation: "اشتراک", theme: "Culture et loisirs", example: "Mon abonnement se termine en juin." },
  { id: "a2-074", term: "se passionner pour", translation: "شیفتهٔ چیزی بودن", theme: "Culture et loisirs", example: "Il se passionne pour l'escalade." },
  { id: "a2-075", term: "s'inscrire", translation: "ثبت‌نام کردن", theme: "Culture et loisirs", example: "Je me suis inscrit à un atelier." },
  { id: "a2-076", term: "emprunter", translation: "قرض گرفتن", theme: "Culture et loisirs", example: "On peut emprunter trois livres." },
  { id: "a2-077", term: "un roman", translation: "رمان", theme: "Culture et loisirs", example: "Je lis un roman en français." },
  { id: "a2-078", term: "un réalisateur", translation: "کارگردان", theme: "Culture et loisirs", example: "Ce réalisateur a reçu un prix." },
  { id: "a2-079", term: "se dérouler", translation: "رخ دادن", theme: "Culture et loisirs", example: "L'histoire se déroule à Paris." },
  { id: "a2-080", term: "divertissant", translation: "سرگرم‌کننده", theme: "Culture et loisirs", example: "Le film est simple mais divertissant." },

  { id: "a2-081", term: "la météo", translation: "آب‌وهوا", theme: "Nature et environnement", example: "Je regarde la météo avant de sortir." },
  { id: "a2-082", term: "un orage", translation: "طوفان همراه رعدوبرق", theme: "Nature et environnement", example: "Un orage est prévu ce soir." },
  { id: "a2-083", term: "la chaleur", translation: "گرما", theme: "Nature et environnement", example: "Je supporte mal la chaleur." },
  { id: "a2-084", term: "un déchet", translation: "زباله", theme: "Nature et environnement", example: "Il faut trier les déchets." },
  { id: "a2-085", term: "économiser", translation: "صرفه‌جویی کردن", theme: "Nature et environnement", example: "Nous essayons d'économiser l'eau." },
  { id: "a2-086", term: "protéger", translation: "محافظت کردن", theme: "Nature et environnement", example: "Chacun peut protéger la nature." },
  { id: "a2-087", term: "pollué", translation: "آلوده", theme: "Nature et environnement", example: "L'air est moins pollué à la campagne." },
  { id: "a2-088", term: "un paysage", translation: "منظره", theme: "Nature et environnement", example: "Le sommet offre un paysage magnifique." },
  { id: "a2-089", term: "une forêt", translation: "جنگل", theme: "Nature et environnement", example: "Nous marchons dans la forêt." },
  { id: "a2-090", term: "le climat", translation: "اقلیم", theme: "Nature et environnement", example: "Le climat change rapidement." },

  { id: "a2-091", term: "être d'accord", translation: "موافق بودن", theme: "Communication et émotions", example: "Je suis d'accord avec cette idée." },
  { id: "a2-092", term: "donner son avis", translation: "نظر دادن", theme: "Communication et émotions", example: "Tout le monde peut donner son avis." },
  { id: "a2-093", term: "se plaindre", translation: "شکایت کردن", theme: "Communication et émotions", example: "Le client se plaint du service." },
  { id: "a2-094", term: "rassurer", translation: "دلگرم کردن", theme: "Communication et émotions", example: "Ses paroles m'ont rassuré." },
  { id: "a2-095", term: "être fier", translation: "افتخار کردن", theme: "Communication et émotions", example: "Je suis fier de mes progrès." },
  { id: "a2-096", term: "être déçu", translation: "ناامید شدن", theme: "Communication et émotions", example: "Il est déçu par le résultat." },
  { id: "a2-097", term: "s'inquiéter", translation: "نگران شدن", theme: "Communication et émotions", example: "Ne t'inquiète pas, tout va bien." },
  { id: "a2-098", term: "proposer", translation: "پیشنهاد کردن", theme: "Communication et émotions", example: "Je vous propose une autre solution." },
  { id: "a2-099", term: "refuser", translation: "رد کردن", theme: "Communication et émotions", example: "Elle a refusé poliment l'invitation." },
  { id: "a2-100", term: "expliquer", translation: "توضیح دادن", theme: "Communication et émotions", example: "Pouvez-vous expliquer cette règle ?" }
];
